const strings = {
  block: "Block",
  transaction: "Transaction",
  inputs: "Inputs",
  outputs: "Outputs",
  lockup: "Lockup",
  reveal: "Reveal",
  recordData: "Data",
  mempool: "Mempool",
  hash: "Hash",
  height: "Height",
  txid: "Txid",
  txsCount: "TXs Count",
  time: "Time",
  size: "Size",
  version: "Version",
  mask: "Mask",
  bits: "Bits",
  difficulty: "Difficulty",
  chainwork: "Chainwork",
  nonce: "Nonce",
  extraNonce: "Extra Nonce",
  fee: "Fee",
  locktime: "Locktime",
  rate: "Rate",
  witness: "Witness",
  hashMerkleRoot: "Hash Merkle Root",
  witnessRoot: "Witness Root",
  treeRoot: "Tree Root",
  reservedRoot: "Reserved Root",
  releaseBlock: "Release Block",
  openHeight: "Last Auction Open Block",
  bidHeightStart: "Bid Period Start",
  revealHeightStart: "Reveal Period Start",
  revealHeightEnd: "Reveal Period End",
  auctionState: "Auction State",
} as const;

export default strings;
