const strings = {
  block: "Block",
  transaction: "Transaction",
  inputs: "Inputs",
  outputs: "Outputs",
  lockup: "Lockup",
  reveal: "Reveal",
  recordData: "Data",
  mempool: "Mempool",
  hash: "Hash",
  height: "Height",
  txid: "Txid",
  txsCount: "Transaction Count",
  time: "Time",
  size: "Size",
  version: "Version",
  mask: "Mask",
  bits: "Bits",
  difficulty: "Difficulty",
  chainwork: "Chainwork",
  nonce: "Nonce",
  extraNonce: "Extra Nonce",
  fee: "Fee",
  locktime: "Locktime",
  rate: "Rate",
  witness: "Witness Hash",
  hashMerkleRoot: "Hash Merkle Root",
  witnessRoot: "Witness Root",
  treeRoot: "Tree Root",
  reservedRoot: "Reserved Root",
  releaseBlock: "Release Block",
  openHeight: "Last Auction Open Block",
  bidHeightStart: "Bid Period Start",
  revealHeightStart: "Reveal Period Start",
  revealHeightEnd: "Reveal Period End",
  auctionState: "Auction State",
  claimAmount: "Claim Amount",
  originName: "Origin Name",
  action: "Action",
  valueTotal: "Total received",
  valueUsed: "Total spent",
  countTotal: "Total outputs",
  countUsedUsed: "Outputs spent",
  received: "Received",
  spent: "Spent",
  address: "Address",
  balance: "Balance",
  bidBlock: "Bid block",
  explorerVersion: "0.2.0",
} as const;

export default strings;
